# MIDTERM PROJECT PETE 686

## Team Members

### 1. Sri Naga Sai Gopala Krishna Kala
### 2. Nandini Shankar

## Task 9 Continued

In [1]:
import numpy as np
import pandas as pd
import pickle

In [2]:
# Load the hold-out data
df_ho = pd.read_csv('Shale_HO.csv')
df_ho.head()

,Operator,TD,TVD,TotalFluid,TotalProppant,TopPerf,BottomPerf,FluidType,LateralLength,ChokeTopDescription,...,Isopach,Porosity,TotalGasBCFPerSection,Temperature,Pressure,KOP,FirstProdDate,minLateralSpacing,numOfOffsetLateralSpacingWells,IP
0,P,17223,9410,453622.0,17822000.0,9772,16998,SLKW,5495.25,0.40625,...,148,0.1179,182.0589,260.34,7023.583841,4429.0,2017,1134.692979,2,10629.713630
1,P,16230,10807,164850.6,5924000.0,11117,16023,SLKW,3647.25,0.25000,...,101,0.1004,86.6555,290.40,8517.600000,5166.5,2016,1308.508694,2,4513.716256
2,P,15246,10211,151578.6,5126660.0,10553,15045,GEL,3412.50,0.31250,...,58,0.0785,73.2662,282.56,8118.045091,4877.0,2015,989.265065,2,3913.974384
3,S,16755,9307,192227.6,13508000.0,9548,16602,GEL,5094.00,0.43750,...,168,0.1100,176.6722,259.58,6987.141841,4226.5,2016,1044.017958,2,12903.008540
4,E,19807,11550,NaN,NaN,11590,17399,NaN,5998.50,0.37500,...,77,0.0839,NaN,298.00,8911.590909,5607.5,2018,445.397387,2,7979.653859

In [3]:
#df_ho['EUR']

In [4]:
with open('label_encoder_operator.pkl', 'rb') as file:
    label_encoder_operator = pickle.load(file)

with open('label_encoder_fluidtype.pkl', 'rb') as file:
    label_encoder_fluidtype = pickle.load(file)

with open('columns_to_drop.pkl', 'rb') as file:
    to_drop = pickle.load(file)

with open('standard_scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

with open('best_model_eur.pkl', 'rb') as file:
    best_model_eur = pickle.load(file)

with open('interpolation_details.pkl', 'rb') as file:
    interpolation_details = pickle.load(file)

In [5]:
df_ho['Operator'] = label_encoder_operator.fit_transform(df_ho['Operator'])

In [6]:
df_ho['FluidType'] = label_encoder_fluidtype.fit_transform(df_ho['FluidType'])

In [7]:
df_ho.head()

,Operator,TD,TVD,TotalFluid,TotalProppant,TopPerf,BottomPerf,FluidType,LateralLength,ChokeTopDescription,...,Isopach,Porosity,TotalGasBCFPerSection,Temperature,Pressure,KOP,FirstProdDate,minLateralSpacing,numOfOffsetLateralSpacingWells,IP
0,1,17223,9410,453622.0,17822000.0,9772,16998,1,5495.25,0.40625,...,148,0.1179,182.0589,260.34,7023.583841,4429.0,2017,1134.692979,2,10629.713630
1,1,16230,10807,164850.6,5924000.0,11117,16023,1,3647.25,0.25000,...,101,0.1004,86.6555,290.40,8517.600000,5166.5,2016,1308.508694,2,4513.716256
2,1,15246,10211,151578.6,5126660.0,10553,15045,0,3412.50,0.31250,...,58,0.0785,73.2662,282.56,8118.045091,4877.0,2015,989.265065,2,3913.974384
3,2,16755,9307,192227.6,13508000.0,9548,16602,0,5094.00,0.43750,...,168,0.1100,176.6722,259.58,6987.141841,4226.5,2016,1044.017958,2,12903.008540
4,0,19807,11550,NaN,NaN,11590,17399,2,5998.50,0.37500,...,77,0.0839,NaN,298.00,8911.590909,5607.5,2018,445.397387,2,7979.653859

In [8]:
df_ho = df_ho.interpolate(method=interpolation_details['method'], order=interpolation_details['order'])

C:\Users\Gopala Kala\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\interpolate\_fitpack2.py:298: UserWarning:
The maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached: s
too small.
There is an approximation returned but the corresponding weighted sum
of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
  warnings.warn(message)

In [9]:
X_ho = df_ho

In [10]:
df_ho = df_ho.drop(columns=to_drop)

In [11]:
df_ho.head()

,Operator,TD,TVD,TotalFluid,TotalProppant,FluidType,ChokeTopDescription,MaxFlowingPSI,MaxShutinPSI,FlowGas,FlowWater,SurfaceX,SurfaceY,Isopach,Porosity,KOP,FirstProdDate,minLateralSpacing,numOfOffsetLateralSpacingWells,IP
0,1,17223,9410,453622.000000,1.782200e+07,1,0.40625,3759,4300.0,11396,791,1608098.552,799114.9713,148,0.1179,4429.0,2017,1134.692979,2,10629.713630
1,1,16230,10807,164850.600000,5.924000e+06,1,0.25000,3775,4043.0,5876,357,1694710.731,836310.3160,101,0.1004,5166.5,2016,1308.508694,2,4513.716256
2,1,15246,10211,151578.600000,5.126660e+06,0,0.31250,4299,4499.0,5006,480,1722800.340,891356.0406,58,0.0785,4877.0,2015,989.265065,2,3913.974384
3,2,16755,9307,192227.600000,1.350800e+07,0,0.43750,4095,4601.0,16812,286,1611520.881,816069.3093,168,0.1100,4226.5,2016,1044.017958,2,12903.008540
4,0,19807,11550,197107.463239,1.674598e+07,2,0.37500,4370,6342.0,8561,420,1715196.831,839920.9428,77,0.0839,5607.5,2018,445.397387,2,7979.653859

In [12]:
X_ho_scaled = scaler.transform(df_ho.drop(['FirstProdDate'], axis=1))

In [13]:
with open('selected_features_indices_eur.pkl', 'rb') as file:
    selected_features_indices_eur = pickle.load(file)

In [14]:
X_ho_scaled_selected_features_eur = X_ho_scaled[:, selected_features_indices_eur]

In [15]:
eur_predictions = best_model_eur.predict(X_ho_scaled_selected_features_eur)

In [16]:
eur_predictions

array([ 8927763.08700069,  8024758.63704344,  7668526.03158913,
       14234855.84822945,  6374665.64111371,  3259500.79197818,
       11549213.73358863,  3486808.78465279,  9582795.82993955,
        9512392.77410225, 16658799.66117936,  8734698.3825078 ])

### Insights

First we loaded the dataset Shale_HO.csv. We opened all the saved pickle files, performed pre-processing steps including one-hot encoding, interpolation of missing data using the saved pre-processors. We scaled the data using the saved StandardScaler. We used the saved best model which was saved in the previous file on the dataset to predict values for EUR on

# END